### ISSUE TITLE
Github command UI refactor

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#102]
![image](https://user-images.githubusercontent.com/26675745/99159383-a0cf0500-2690-11eb-8f08-3162839d16e9.png)

Instead of having multiple embeds, return 1

![image](https://user-images.githubusercontent.com/26675745/99159411-ee4b7200-2690-11eb-97a1-8166442ac9bc.png)

Wrap command usage in \` and use the naming convention as stated [here](https://github.com/SCE-Development/SCE-discord-bot/wiki/Example-naming-convention)

**Comment by charlotte-zhuang** [comment]
`s!git commits <repo> [num]` has some unexpected behavior when the user enters a negative number.
