### ISSUE TITLE
Set up Mongo + GQL on EC2 instance

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#106]
On EC2 Instance set up MongoDB with GraphQL endpoint. Make sure gql can only be accessed by the bot and there are no additional open ports

**Comment by jerrylee17** [comment]
https://www.apollographql.com/docs/apollo-server/security/authentication/#schema-authorization

**Comment by charlotte-zhuang** [comment]
76176a9ad0e4d70ac1054f04c1a20ff73555a018 sets up MongoDB. There's an endpoint too, but that's not really used for anything so I'm not sure if it's even working. Nothing is public facing, so that won't be an issue yet.
