### ISSUE TITLE
Game: Easter Egg Hunt

### ISSUE THREAD

**Issue by Christopher-Tom** [SCE-Development/SCE-discord-bot#120]
There are three different "spawning methods" of eggs.
This game is a friendly competition to see who can first find all easter eggs.
1. Time based egg spawning spawns an easter egg after a certain amount of time passes, first to claim the egg will receive it. 
2. Activity based egg spawning spawns an easter egg after a certain number of chat messages within the active channel are sent. The first to claim the egg will receive it.
3. Hidden Codes throughout SCE media are input into the bot to add eggs to your basket.

## commands

`s!egghunt` displays the list of commands and information about the game.
`s!egghunt grab` adds the egg from the spawning events to your basket if you are the first to claim it.
`s!egghunt claim <egg code>` claims the egg associated with the egg code.  *egg code is an English word
`s!egghunt leaderboard` displays the list of users participating in the egg hunt and the number of eggs each user has.
`s!egghunt eggs` displays the list of eggs and where to find them. 
`s!egghunt basket` displays a list of eggs you have collected.
`s!egghunt admin start <channel name>` configures the bot to read messages and send them within the specified channel.
`s!egghunt admin stop [channel name]` stops the bot from reading messages and sending them within the specified channel. If no channel is specified, all instances are stopped.
`s!egghunt admin add` prompts the user to give a name for the egg and a link to the image the user wants the egg to have and then adds the egg to the egghunt eggs list.
`s!egghunt admin remove <name of egg>` removes the egg from the egghunt eggs list.
`s!egghunt admin hardreset` completely clears all saved data of eggs collected on all users.

**Comment by charlotte-zhuang** [comment]
## Schema

```graphql
Egg {
  guildID: {
    type: String,
    required: true
  },
  name: {
    type: String,
    required: true
  },
  imageUrl: {
    type: String,
    required: false
  },
  code: {
    type: String,
    required: false
  },
  description: {
    type: String,
    required: false
  },
  hint: {
    type: String,
    required: false
  }
}
```

```graphql
EggBasket: {
  guildID: {
    type: String,
    required: true
  },
  userID: {
    type: String,
    required: true
  },
  eggs: [
    {
      type: Egg
    }
  ]
}
```

**Comment by charlotte-zhuang** [comment]
## Guild Config Schema

```qql
GuildConfig {
    guildID: {
       type: String,
       required: true,
    },
    eggHunt: {
        channels: [
              {
                  type: String,
              }
        ]
    }
}
```

This is a general schema for guild specific configuration. It will hold the channels that eggs are spawning in.

**Comment by charlotte-zhuang** [comment]
I made some changes to the schemas on easter-api and will update once they're finished.
