### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by charlotte-zhuang** [SCE-Development/SCE-discord-bot#124]
We should have a privacy policy for end users of our bot.

command: `s!privacy`

- displays either a link to the policy or the policy itself.

**Comment by qsaml** [comment]
what would be the policy of using our bot though?

**Comment by charlotte-zhuang** [comment]
This would be a privacy policy, so information on the data we store and collect and how we use user data.

**Comment by jerrylee17** [comment]
[Privacy Policy](https://github.com/SCE-Development/SCE-discord-bot/wiki/Privacy-Policy)
