### ISSUE TITLE
Add Autorole Funcitonality

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/SCE-discord-bot#26]
When a user joins our discord, we should be able to automatically assign them a role as `Member`, and if they are a bot, assign them a `bot` role. We would need to listen for user's joining our server, as the Tastymaki bot does already below:
![image](https://user-images.githubusercontent.com/36345325/78512226-8ffffd80-7757-11ea-8a26-0c29a4c5d655.png)

### How to get this done
1. Add a listener in [`server.js`](https://github.com/SCE-Development/SCE-discord-bot/blob/master/server.js) Like below:
```js
client.on("guildCreate", function(guild){
    console.log(`the client joins a guild`);
});
```
2. @jerrylee17 where in the [discord.js docs](https://discord.js.org/#/docs/main/) does it talk about assigning roles?

**Comment by jerrylee17** [comment]
When someone joins the server, give them the member role. If the person that joins is a bot, give them a bot role

**Comment by jerrylee17** [comment]
For role assignment, see `joinStudychannel.js`
