### ISSUE TITLE
Add reaction role functionality

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/SCE-discord-bot#27]

**Comment by jerrylee17** [comment]
Allow users to set up a reaction role. A reactionrole is basically where you react to a message with a certain emote and get a role. 

Type rr!reactionrole in the server to test how it works

**Comment by jerrylee17** [comment]
Name: s!reactionrole
Description: Create a command that allows you to set a reaction role
Category: configuration
Aliases: rr (?)
Permissions: admin

This will pop up an embed that prompts you to enter: 
ChannelID, messageID, type of reactionrole, reaction, role/roleID
