### ISSUE TITLE
List of current commands that need refactoring

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#63]
Functionality
1. `cct.js` -->Honestly could remove this role since it is not really important

UI
1. `createStudyChannel.js`
1. `deleteStudyChannel.js`
1. `joinStudyChannel.js`
1. `help.js`

**Comment by jerrylee17** [comment]
1. create study channel
Make embed for reply messages
1. delete study channel
Make embed for reply messages
1. join study channel
Make embed for reply messages
1. help.js
Hide server management/mod from normal users
1. Overall command architecture
Rather than checking author permissions within execute, utilize the `permissions: 'admin'` portion of a command to determine if a user can execute it

**Comment by RTX-Banana** [comment]
Refactored s!help and part of s!git commands.
Reordered the parameters for all commands to match the order shown in Command.js.
Added disabled parameter and implemented disabled functionality in CommandHandler.js.
resolved #63
