### ISSUE TITLE
Study channel management

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#66]
**Purge study channels**

`s!purgestudychannels` / `s!psc` deletes all study channels that have not had a new message for over 30 days.

Reason for this command: There may be a lot of clutter having so many study channels. Thus, purging them is a good idea

**Archive study channels**
`s!archivestudychannel` / `s!asc` downloads the contents of the channel into a txt file

Reason for this command: Some people may want to save their work

**Alphabetize study channels** (Done)
When calling `s!csc`, Reorder the channels alphabetically

**Comment by hsorathia** [comment]
:0

**Comment by charlotte-zhuang** [comment]
## Archive channel (instead of archive study channels)
`s!archivechannel` / `s!ac` downloads the contents into a txt file and downloads images.
Reason for this command: to remove old channels without losing content.

## Purge study channels
Change to channels without activity for 180 days.
