### ISSUE TITLE
Custom threads

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#76]
- To start a thread, `type s!thread <Message>`
  - The messageID is now at the beginning of the thread
  - The thread is given a threadID
- To view all threads, type s!thread
  - Threads inactive for over a week will not be displayed
- To add onto a thread, type |\<threadID>| \<message>
  - For example: |1| Your code is wrong
- To view a full thread, type  |\<threadID>|
  - Result will be displayed in an embed
  - Example of a displayed thread: 
**Jerry**: Your code is bad
**Habib**: No it's not
**Isita**: Jerry why is Habib's code bad
**Jerry**: Idk
- Thread management (s!threadmanagement or s!tm)
  - s!tm remove \<ThreadID>
    - Alias rm
    - Remove a thread
  - s!tm create
    - Creates a thread
    - Message displays ThreadID

**Comment by hsorathia** [comment]
🤔

**Comment by jerrylee17** [comment]
Ideally this would have a team of 4 (experienced programmers). Should designate a whole folder in api/ and src/ for this. Also may need its own command handler. 
Needs extensive planning so the code is scalable for the future. 
- ER diagram
- UML (possibly)
- Architecture

**Comment by jerrylee17** [comment]
**ER Diagram**
![image](https://user-images.githubusercontent.com/26675745/95937349-71289680-0d8c-11eb-86ec-abf92704a21d.png)


**Architecture**
![image](https://user-images.githubusercontent.com/26675745/95937326-5c4c0300-0d8c-11eb-95f5-29b9144d0398.png)

**Comment by jerrylee17** [comment]
The difference between `threadManager` and `thread` is that `threadManager` can be used by officers

**Comment by jerrylee17** [comment]
Meeting Oct 13: 
**Charlotte**
Handlers

**Isita**
Threads

**Patrick**
NonPrefixCommands

**Jerry**
Backend GraphQL

**Comment by jerrylee17** [comment]
Meeting November 17:

## Tasks

**Jerry**
Thread ID generator

**Charlotte**
Finish tm/thread

**Patrick**
Finish up your part noob

**Comment by jerrylee17** [comment]
Meeting Dec 1: 

### Tasks
- Make regex string matching on mongo (match the ID - 4+ digits, if there's more than one, pop up modal for choose one)
- ID gen - 11 digits of inverted createdTimestamp
- Modify `s!threadmannager` to autogen the ID
- push `s!thread` and `s!threadmanager` code
- Host (See #106)

### Going forward (Extra stuff)
Archiving threads to txt (in case there are inactive ones)

Meet Dec 15

**Comment by charlotte-zhuang** [comment]
All the original requirements are met and there are new issues for the extra stuff.
