### ISSUE TITLE
Bot crash recovery

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#81]
The discord bot crashed today for some reason. I restarted the bot manually by killing its process and relaunching the docker image. 

If possible, I would like the bot to ping itself at a certain time every day to make sure that it is up. 

If bot crashes
1. Store the details of the error in a separate file
1. Launch another container with `docker-compose up`
1. Kill the container that is not working
1. Ping newly created container to make sure it works
1. If it does not respond, repeat this process a maximum of 5 times while logging that the bot is down
1. Send a message in serverconfig alerting officers of the bot crash with the reason (**Note: My thought here is "how is the bot going to communicate with the server if it is down"**)

This should maximize the uptime of the bot.

To be honest, I'll need to know a lot more about discordJS/docker before being able to implement this

**Comment by evanugarte** [comment]
this was resolved with #195
