### ISSUE TITLE
Use bot to record meetings

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#82]
One of the primary reasons why Zoom is so popular over Discord is that it can record meetings. This PR will add the functionality to record meetings and store it somewhere (s3 bucket maybe). 
`s!record start` to record the channel that the user is in
`s!record stop` to stop recording
`s!record all` to get a link to get all recordings

This project can be linked to Core-v4.

**Comment by hsorathia** [comment]
Some notes and things to consider:
1. Where are you saving the current buffer for the recordings. Will it be on the local db?
2. How big can the recordings be? What if someone starts a recording and never ends it.
3. How often are you going to access s3? If you access too often, it can [get pricy](https://aws.amazon.com/s3/pricing/)

After doing a brief search I found two discord bots ([jda](https://top.gg/bot/376095684069163008) and [craig](https://top.gg/bot/craig)) that also implement this functionality. There's also pawa and some others, so maybe we can see how they do it as well or how they addressed some issues.

This is pretty cool stuff tho

**Comment by jerrylee17** [comment]
> Some notes and things to consider:
> 
> 1. Where are you saving the current buffer for the recordings. Will it be on the local db?
> 2. How big can the recordings be? What if someone starts a recording and never ends it.
> 3. How often are you going to access s3? If you access too often, it can [get pricy](https://aws.amazon.com/s3/pricing/)
> 
> After doing a brief search I found two discord bots ([jda](https://top.gg/bot/376095684069163008) and [craig](https://top.gg/bot/craig)) that also implement this functionality. There's also pawa and some others, so maybe we can see how they do it as well or how they addressed some issues.
> 
> This is pretty cool stuff tho

1. s3 bucket for recordings. Everything else in local db (recording date/time/etc, s3 bucket link). 
2. Recording ends automatically when user leaves voice channel
3. Only time you access it is when someone views the recording. If possible, remove the option to view and only give an option to download

**Comment by qsaml** [comment]
> > Some notes and things to consider:
> > 
> > 1. Where are you saving the current buffer for the recordings. Will it be on the local db?
> > 2. How big can the recordings be? What if someone starts a recording and never ends it.
> > 3. How often are you going to access s3? If you access too often, it can [get pricy](https://aws.amazon.com/s3/pricing/)
> > 
> > After doing a brief search I found two discord bots ([jda](https://top.gg/bot/376095684069163008) and [craig](https://top.gg/bot/craig)) that also implement this functionality. There's also pawa and some others, so maybe we can see how they do it as well or how they addressed some issues.
> > This is pretty cool stuff tho
> 
> 1. s3 bucket for recordings. Everything else in local db (recording date/time/etc, s3 bucket link).
> 2. Recording ends automatically when user leaves voice channel
> 3. Only time you access it is when someone views the recording. If possible, remove the option to view and only give an option to download

- in order to do that, it'd be necessary to add some sort of command to call the bot to the vc `s!join` or something
- for privacy issues, maybe the bot should ask the user who calls the bot to the vc if they want it to record them or not

**Comment by jerrylee17** [comment]
> > > Some notes and things to consider:
> > > 
> > > 1. Where are you saving the current buffer for the recordings. Will it be on the local db?
> > > 2. How big can the recordings be? What if someone starts a recording and never ends it.
> > > 3. How often are you going to access s3? If you access too often, it can [get pricy](https://aws.amazon.com/s3/pricing/)
> > > 
> > > After doing a brief search I found two discord bots ([jda](https://top.gg/bot/376095684069163008) and [craig](https://top.gg/bot/craig)) that also implement this functionality. There's also pawa and some others, so maybe we can see how they do it as well or how they addressed some issues.
> > > This is pretty cool stuff tho
> > 
> > 
> > 
> > 1. s3 bucket for recordings. Everything else in local db (recording date/time/etc, s3 bucket link).
> > 2. Recording ends automatically when user leaves voice channel
> > 3. Only time you access it is when someone views the recording. If possible, remove the option to view and only give an option to download
> 
> * in order to do that, it'd be necessary to add some sort of command to call the bot to the vc `s!join` or something
> * for privacy issues, maybe the bot should ask the user who calls the bot to the vc if they want it to record them or not

`s!record start` should handle the join. the `record` option should only be available to officers.
