### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/SCE-discord-bot#96]
Add a command that can store custom non prefix commands. 

For example:
`s!customCommand` or `s!cc` prompts a 2 stage embed
Stage 1: Enter the command (`h!treedat`)
Stage 2: Enter the response (`<@238501291532222464>`)

Command: `h!treedat`
Response: <@238501291532222464>
^^ That pings habib

**Comment by charlotte-zhuang** [comment]
## Changes

1. Custom commands will be prefixed commands
2. Usage: `s!cc <command>` to trigger the command
3. Also add functionality to view commands and for officers to delete commands
4. `s!cc` then select to view all commands or remove a command
